name: CI - Unit Tests

on: [push]

env:
  NODE_VERSION: "22"

jobs:
  link:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Check Prettier Formatting
        run: yarn format
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test:unit
        env:
          PORT: 3000
          NODE_ENV: test
          JWT_SECRET: mysecretkey
          JWT_EXPIRATION_TIME: 86400
          DATABASE_URL: fake_url
